### ISSUE TITLE
README.md のteamsのリンクを書き換えたい

### ISSUE THREAD

**Issue by ShuzoN** [zucks/the-zen-of-zucks#14]
teamsというエンジニアチームに関する情報をまとめたページが有る
もともとあったものをコーポレートサイトに移管した。移行期間として一定期間を過ぎたため、ページとしてもcloseしたい
被リンク調査を行ったところ、the-zen-of-zucksでリンクされていることを知った。

![image](https://github.com/user-attachments/assets/c5386e36-e8a0-4f47-a80a-a38802f3e4d2)

`https://techblog.cartaholdings.co.jp/zucks` を `https://cartaholdings.co.jp/engineering/teams/carta-marketing-firm/` に変更したい

prを送ろうとしたが私にはwrite権限がないため修正できない。ということでどなたか改修よろしくです

![image](https://github.com/user-attachments/assets/93c8fbd0-8b38-4e8a-92f0-36e2235d75a6)

**Comment by tomeito** [comment]
https://github.com/zucks/the-zen-of-zucks/pull/15 で対応した
